### ISSUE TITLE
Use notification rather than poll for network interface changes

### ISSUE THREAD

**Issue by fumoboy007** [hbwhite/Clutch#1]
Currently, `ClutchAgent` checks every 10 seconds for network interface changes. From my understanding, this is not ideal because it could leave a 10-second gap where Transmission is sending/receiving traffic through a different network interface when the bound network interface changes or disappears.

There should be some way to receive a notification upon network interface changes. This [StackOverflow answer](https://stackoverflow.com/a/42093698/815742) may point us in the right direction.

**Comment by hbwhite** [comment]
Because Clutch will bind Transmission to an IP address, if the interface address changes in that 10-second gap, it will continue to try sending traffic over the old IP address, which won’t be able to route traffic (unless you start a new server on that IP address in that interval). For this reason it shouldn’t be a problem.

I looked for a way to receive a notification when the interface IP address changes. I haven’t tried the approach you linked to yet. Linux has an option for sockets, SO_BINDTODEVICE, that isn’t present on Mac OS. Vuze uses the same polling technique to implement interface binding on its Mac client.

If you’re able to get notifications working, send me a pull request and I’ll check it out!

I’m glad to see people are using the app; I think more clients need an interface binding option on Mac.

**Comment by fumoboy007** [comment]
> Because Clutch will bind Transmission to an IP address, if the interface address changes in that 10-second gap, it will continue to try sending traffic over the old IP address, which won’t be able to route traffic (unless you start a new server on that IP address in that interval). For this reason it shouldn’t be a problem.

Right. A 10-second poll is probably “good enough”, but a notification would be ideal.

> I’m glad to see people are using the app; I think more clients need an interface binding option on Mac.

I agree that this should be a feature built into Transmission. Hopefully someone gets around to this [9-year-old feature request](https://trac.transmissionbt.com/ticket/2313). In the meantime, we can use Clutch. Thank you so much for building this!

**Comment by SwedenGuy** [comment]
There used to be a program called Transmission Interface Binder that had the exact same function as your program.  It still works, but gives a few confusing messages.  Maybe reach out the guy who coded it and see if he is willing to show you his code?

https://libraries.io/github/joshbernfeld/Transmission-Interface-Binder
