### ISSUE TITLE
Change in interface causes data loss

### ISSUE THREAD

**Issue by SwedenGuy** [hbwhite/Clutch#3]
It seems that if the interface goes down, Clutch causes Transmission to do a hard exit somehow so any files that were in the process of being downloaded are lost.  The exit should be graceful so you save your progress...

**Comment by hbwhite** [comment]
Telling Transmission to quit normally will cause it to present an "Are you sure you want to quit?" dialog instead of quitting. If the user isn't present to answer this dialog, Transmission won't ever quit, so it won't be able to send any traffic over the new interface address. This would be a problem for users who are downloading torrents overnight.

For this reason, Clutch will force-quit Transmission to avoid the dialog so it can continue to download files. If lots of people have issues with this, I can add an option to quit Transmission normally (with the dialog).

**Comment by hbwhite** [comment]
Version 1.4 fixes this issue with its new “graceful restart” option.

You can update the app via Clutch > Check for Updates, or you can download the latest version from the “Releases” page on GitHub.

Enjoy! -H
