### ISSUE TITLE
novice user - ? binding to correct ip

### ISSUE THREAD

**Issue by chimfieldblue** [hbwhite/Clutch#7]
Hi there,
great app. many thanks for your work.
I am using a vpn with variable IP. 
If I bind to utun0, does this just bind to whatever IP the vpn is over (cf a specific one?)
do you have a basic manual for novices like me :) ?
regards
cfb

**Comment by hbwhite** [comment]
Yes, if you bind to utun0, Clutch will have it bind to whatever IP utun0 is using.

If the IP of utun0 changes, Clutch automatically binds Transmission to the new IP (it will automatically restart Transmission afterward). When this happens, Transmission is unable to send any traffic until it binds to the new IP (since the old IP will have disappeared).

I hope this helps!
